name: build-documentation
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ main ]

permissions: write-all

jobs:
  build-docc:
    runs-on: [macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Documentation
        run: sh ./.github/scripts/build-docc.sh
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
        
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs
          force: true
          directory: ./docs